spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo
mybatis:
  config-location: classpath:config/sqlmaper.xml
  mapper-locations: classpath:mapper/*.xml
